/**
 * WASM implementation of the BintAPI.
 *
 * This wraps the wasm-bindgen generated WebSession to provide
 * a consistent async API. The primary interface is through execute()
 * which runs bint commands, keeping the API consistent with potential
 * HTTP server backends.
 */

import { BintAPI } from './api.js';
import { events, Events } from './events.js';

/**
 * Coerce a value that the wasm boundary may have serialized as a
 * BigInt (because we configure serde-wasm-bindgen with
 * `serialize_large_number_types_as_bigints(true)` for u64-safety on
 * addresses) into a regular JS Number — appropriate for fields we
 * know to be small in practice (state indices, register counts,
 * lengths). Calling JS sites can compare against literal numbers
 * without tripping over `0 !== 0n`.
 *
 * Use this only on integers that genuinely fit in 2^53 — addresses
 * and 64-bit values must stay BigInt.
 *
 * @param {number|bigint|null|undefined} v
 * @returns {number}
 */
export function asIndex(v) {
    if (typeof v === 'bigint') return Number(v);
    if (typeof v === 'number') return v;
    return 0;
}

// SLEIGH spec URL mapping
// Keys are canonical SLEIGH IDs, values are URL paths to pre-compiled bincode files
const SLEIGH_SPECS = {
    'x86:LE:32:default': '/sleigh/x86_LE_32_default.bincode',
    'x86:LE:64:default': '/sleigh/x86_LE_64_default.bincode',
    'AARCH64:LE:64:v8A': '/sleigh/AARCH64_LE_64_v8A.bincode',
    'ARM:LE:32:v8': '/sleigh/ARM_LE_32_v8.bincode',
    'MIPS:BE:32:default': '/sleigh/MIPS_BE_32_default.bincode',
    'MIPS:LE:32:default': '/sleigh/MIPS_LE_32_default.bincode',
    'MIPS:BE:64:default': '/sleigh/MIPS_BE_64_default.bincode',
    'MIPS:LE:64:default': '/sleigh/MIPS_LE_64_default.bincode',
    'RISCV:LE:32:default': '/sleigh/RISCV_LE_32_default.bincode',
    'RISCV:LE:64:default': '/sleigh/RISCV_LE_64_default.bincode',
    'PowerPC:BE:32:default': '/sleigh/PowerPC_BE_32_default.bincode',
    'PowerPC:BE:64:default': '/sleigh/PowerPC_BE_64_default.bincode',
    'PowerPC:LE:64:default': '/sleigh/PowerPC_LE_64_default.bincode',
    'sparc:BE:32:default': '/sleigh/sparc_BE_32_default.bincode',
    'sparc:BE:64:default': '/sleigh/sparc_BE_64_default.bincode',
    '68000:BE:32:default': '/sleigh/68000_BE_32_default.bincode',
    'avr8:LE:16:default': '/sleigh/avr8_LE_16_default.bincode',
};

// Architecture → SLEIGH spec resolution lives in Rust now (see
// Session::sleigh_language_id). Earlier we duplicated the table here
// AND in bint-decompile-view.js AND in src/arch/sleigh/cache.rs — and
// every copy had the same MIPS-endianness bug. The wasm session
// computes the right spec id from the loaded binary's metadata; JS
// just asks for it.

export class WasmAPI extends BintAPI {
    constructor() {
        super();
        this.wasm = null;
        this.session = null;
        this.initialized = false;
        this.loadedSpecs = new Set();
    }

    /**
     * Initialize the WASM module.
     * Must be called before any other methods.
     * @returns {Promise<void>}
     */
    async init() {
        if (this.initialized) return;

        // Import the WASM module (generated by wasm-pack)
        const wasm = await import('/wasm/bint.js');
        await wasm.default();

        this.wasm = wasm;
        this.session = new wasm.WebSession();
        this.initialized = true;

        console.log(`bint WASM initialized, version ${this.session ? wasm.version() : 'unknown'}`);
    }

    /**
     * Ensure WASM is initialized.
     */
    ensureInit() {
        if (!this.initialized) {
            throw new Error('WASM not initialized. Call init() first.');
        }
    }

    async loadBinary(data, filename) {
        this.ensureInit();

        // Cache the bytes + metadata so views that need the raw image
        // (e.g. the decompile panel, which hands them to a Web Worker)
        // don't have to round-trip through `file data /j` base64.
        this._currentBytes = data;

        // load_binary returns JSON table from 'info general /j'
        const result = this.session.load_binary(data, filename);
        const tableRows = JSON.parse(result);

        // Parse table format into flat metadata object
        // Table format: [{property: {value: "Format"}, value: {value: "ELF"}}, ...]
        const metadata = this._parseInfoTable(tableRows);
        this._currentMetadata = metadata;

        // Auto-load SLEIGH spec for this architecture. The wasm session
        // knows the right id (LE/BE, 32/64 bits) from the binary it
        // just opened — single source of truth.
        const archId = this.session.sleigh_language_id();
        if (archId && !this.loadedSpecs.has(archId)) {
            await this.autoLoadSleighSpec(archId);
        }

        events.emit(Events.BINARY_LOADED, metadata);
        return metadata;
    }

    /** Raw bytes of the currently-loaded binary, or null. */
    getCurrentBytes() { return this._currentBytes || null; }
    /** Parsed metadata of the currently-loaded binary, or null. */
    getCurrentMetadata() { return this._currentMetadata || null; }

    /**
     * Replace the in-process bint Session with a fresh one and drop
     * cached file state. Used by the web frontend to simulate a clean
     * "new instance" when the user opens a second binary, without
     * requiring a full page reload.
     *
     * SLEIGH specs are kept in `loadedSpecs` and re-uploaded into the
     * new session lazily by load_binary's auto-load path, so users
     * don't pay to re-download spec files just to switch binaries.
     */
    resetSession() {
        this.ensureInit();
        if (this.session && typeof this.session.free === 'function') {
            this.session.free();
        }
        this.session = new this.wasm.WebSession();
        this._currentBytes = null;
        this._currentMetadata = null;
        // Forget which specs the *previous* session had loaded — the
        // new Rust-side Session knows nothing about them yet.
        this.loadedSpecs = new Set();
    }

    /**
     * Snap an address to the entry of the function containing it.
     * Uses the session's NameSpace plus a bounded backward
     * prologue-pattern scan. Returns the resolved entry as a BigInt;
     * 64-bit virtual addresses (Mach-O AArch64 starts at 0x100000000)
     * are routine, so Number would silently corrupt values past 2^53
     * — keep everything in BigInt and let callers convert at display
     * time.
     *
     * Accepts string (hex or decimal), Number, or BigInt input.
     */
    resolveFunctionEntry(address) {
        this.ensureInit();
        const addrBig = typeof address === 'bigint' ? address : BigInt(address);
        const entry = this.session.resolve_function_entry(addrBig);
        return typeof entry === 'bigint' ? entry : BigInt(entry);
    }

    /**
     * Read `size` bytes at virtual address `address` from the loaded
     * binary, honouring per-segment mapping (so addresses across
     * non-contiguous Mach-O segments resolve correctly). Returns a
     * Uint8Array; empty if no binary is loaded or the read fails.
     */
    readAt(address, size) {
        this.ensureInit();
        const addrBig = typeof address === 'bigint' ? address : BigInt(address);
        return this.session.read_at(addrBig, size);
    }

    /**
     * Parse info general output into flat metadata object.
     * Handles two formats:
     * - New PropertyTable format: flat object {format: "ELF", architecture: "x86_64", ...}
     * - Legacy table format: array [{property: {value: "Format"}, value: {value: "ELF"}}, ...]
     * @param {Object|Array} data - JSON output from info general
     * @returns {Object} Flat metadata object
     */
    _parseInfoTable(data) {
        // Check if this is the new PropertyTable format (flat object with known keys)
        if (data && typeof data === 'object' && !Array.isArray(data)) {
            // New format - already flat, just normalize values
            const metadata = {};

            // Direct mappings
            if (data.format !== undefined) metadata.format = data.format;
            if (data.architecture !== undefined) metadata.architecture = data.architecture;

            // Entry point - keep as hex string for 64-bit address support
            if (data.entry_point !== undefined) metadata.entry_point = String(data.entry_point);

            // File size - could be number or string
            if (data.file_size !== undefined) {
                metadata.file_size = typeof data.file_size === 'number'
                    ? data.file_size
                    : parseInt(data.file_size, 10) || 0;
            }

            // Word size - convert "64-bit" string or direct value
            if (data.word_size !== undefined) {
                metadata.is_64_bit = data.word_size === '64-bit' || data.word_size === 64;
            }

            // Endianness - convert string or direct value
            if (data.endianness !== undefined) {
                metadata.is_little_endian = data.endianness === 'little' ||
                    data.endianness === 'Little-endian' ||
                    data.endianness === true;
            }

            // Counts
            if (data.section_count !== undefined) {
                metadata.section_count = typeof data.section_count === 'number'
                    ? data.section_count
                    : parseInt(data.section_count, 10) || 0;
            }
            if (data.symbol_count !== undefined) {
                metadata.symbol_count = typeof data.symbol_count === 'number'
                    ? data.symbol_count
                    : parseInt(data.symbol_count, 10) || 0;
            }

            return metadata;
        }

        // Legacy table format (array of rows)
        const rows = data;
        const metadata = {};
        const keyMap = {
            'Format': 'format',
            'Architecture': 'architecture',
            'Entry Point': 'entry_point',
            'File Size': 'file_size',
            'Word Size': 'is_64_bit',
            'Endianness': 'is_little_endian',
            'Sections': 'section_count',
            'Symbols': 'symbol_count',
        };

        for (const row of rows) {
            // Handle {property: {type: "comment", value: "X"}, value: {type: "Y", value: "Z"}} format
            const propCell = row.property;
            const valCell = row.value;

            // Extract property name from nested structure
            const propName = propCell?.value || propCell;

            // Extract value - handle nested {type, value} objects or plain strings
            let propValue;
            if (typeof valCell === 'object' && valCell !== null) {
                propValue = valCell.value;
            } else {
                propValue = valCell;
            }

            const metaKey = keyMap[propName];
            if (metaKey) {
                // Parse values appropriately
                if (metaKey === 'entry_point') {
                    // Keep entry_point as hex string for 64-bit address support
                    metadata[metaKey] = String(propValue);
                } else if (metaKey === 'file_size') {
                    // "154624 bytes" -> 154624
                    metadata[metaKey] = parseInt(propValue, 10) || 0;
                } else if (metaKey === 'section_count' || metaKey === 'symbol_count') {
                    metadata[metaKey] = parseInt(propValue, 10) || 0;
                } else if (metaKey === 'is_64_bit') {
                    // "64-bit" or "32-bit"
                    metadata[metaKey] = propValue === '64-bit';
                } else if (metaKey === 'is_little_endian') {
                    // "Little-endian" or "Big-endian"
                    metadata[metaKey] = propValue === 'Little-endian';
                } else {
                    metadata[metaKey] = propValue;
                }
            }
        }

        return metadata;
    }

    /**
     * Automatically fetch and load a SLEIGH spec.
     */
    async autoLoadSleighSpec(archId) {
        const url = SLEIGH_SPECS[archId];
        if (!url) {
            console.warn(`No SLEIGH spec URL for architecture: ${archId}`);
            return false;
        }

        try {
            console.log(`Fetching SLEIGH spec: ${url}`);
            const response = await fetch(url);
            if (!response.ok) {
                console.warn(`Failed to fetch SLEIGH spec: ${response.status}`);
                return false;
            }

            const data = new Uint8Array(await response.arrayBuffer());
            return await this.loadSleighSpec(archId, data);
        } catch (e) {
            console.warn(`Error loading SLEIGH spec for ${archId}:`, e);
            return false;
        }
    }

    async loadSleighSpec(archId, data) {
        this.ensureInit();

        const success = this.session.load_sleigh_spec(archId, data);
        if (success) {
            this.loadedSpecs.add(archId);
            console.log(`Loaded SLEIGH spec: ${archId}`);
        }
        return success;
    }

    async execute(command) {
        this.ensureInit();

        try {
            const result = this.session.execute(command);
            events.emit(Events.COMMAND_EXECUTED, { command, result });
            return result;
        } catch (e) {
            // Handle quit command specially
            if (e === 'quit') {
                events.emit(Events.COMMAND_EXECUTED, { command, quit: true });
                return '';
            }
            events.emit(Events.COMMAND_ERROR, { command, error: e });
            throw e;
        }
    }

    async hasBinary() {
        this.ensureInit();
        return this.session.has_binary();
    }

    async getVersion() {
        this.ensureInit();
        return this.wasm.version();
    }

    // ---- Seek navigation (overrides BintAPI's text-command versions) ----
    //
    // The base class issues `seek` / `seek <addr>` / `seek back` / `seek
    // forward` and parses the textual output. Here we go straight to the
    // typed wasm methods. We still emit SEEK_CHANGED with a hex string so
    // every other component (which keys off that event) keeps working.

    async getSeek() {
        this.ensureInit();
        const addr = this.session.get_seek();
        return '0x' + addr.toString(16);
    }

    async setSeek(addr) {
        this.ensureInit();
        const big = typeof addr === 'bigint' ? addr : BigInt(addr);
        this.session.set_seek(big);
        const hexAddr = '0x' + big.toString(16);
        events.emit(Events.SEEK_CHANGED, hexAddr);
    }

    async seekBack() {
        this.ensureInit();
        const out = this.session.seek_back();
        // NavigateOutput.to is null at the boundary of history.
        if (!out || out.to == null) return null;
        const hex = '0x' + out.to.toString(16);
        events.emit(Events.SEEK_CHANGED, hex);
        return hex;
    }

    async seekForward() {
        this.ensureInit();
        const out = this.session.seek_forward();
        if (!out || out.to == null) return null;
        const hex = '0x' + out.to.toString(16);
        events.emit(Events.SEEK_CHANGED, hex);
        return hex;
    }

    async canSeekBack() {
        this.ensureInit();
        const h = this.session.seek_history();
        // `current_index` arrives as a BigInt at the wasm boundary
        // (usize via serde-wasm-bindgen). Earlier versions of this
        // method tested `typeof === 'number'` which never holds for
        // BigInt and left the back/forward buttons permanently
        // disabled. `asIndex` normalises the value either way.
        if (h?.current_index === null || h?.current_index === undefined) return false;
        return asIndex(h.current_index) > 0;
    }

    async canSeekForward() {
        this.ensureInit();
        const h = this.session.seek_history();
        if (h?.current_index === null || h?.current_index === undefined) return false;
        if (!Array.isArray(h.entries)) return false;
        return asIndex(h.current_index) < h.entries.length - 1;
    }

    async getFileData() {
        this.ensureInit();
        if (!await this.hasBinary()) return null;
        return this.session.file_data();
    }
}

// Singleton instance
let instance = null;

/**
 * Get or create the WasmAPI instance.
 * @returns {WasmAPI}
 */
export function getWasmAPI() {
    if (!instance) {
        instance = new WasmAPI();
    }
    return instance;
}

export default WasmAPI;
